name: Build 32-bit x86 bzImage Kernel

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          gcc-10 g++-10 gcc-10-multilib g++-10-multilib \
          binutils binutils-i686-linux-gnu \
          bc bison flex libssl-dev libelf-dev dwarves \
          build-essential libncurses-dev \
          cmake git libdw-dev libdwarf-dev zlib1g-dev libiberty-dev

    - name: Build and install pahole v1.22
      run: |
        git clone https://git.kernel.org/pub/scm/devel/pahole/pahole.git -b v1.22
        cd pahole
        mkdir build && cd build
        cmake .. \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DCMAKE_INSTALL_LIBDIR=lib \
          -DEXEC_INSTALL_PREFIX= \
          -D__LIB=lib
        make -j$(nproc)
        sudo make install
        echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/dwarves.conf
        sudo ldconfig
        echo "LD_LIBRARY_PATH=/usr/local/lib" >> $GITHUB_ENV
        pahole --version

    - name: Set GCC and LD versions
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        echo "GCC Version:"
        gcc --version
        echo "LD Version:"
        ld --version

    - name: Clone kernel source
      run: |
        git clone https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git -b v5.10 kernel
        patch -d kernel -p1 < patch/elf.patch

    - name: Use x86_64_defconfig
      working-directory: kernel
      run: |
        make x86_64_defconfig

        # 启用 BPF / Netfilter / XDP
        scripts/config --enable CONFIG_BPF
        scripts/config --enable CONFIG_BPF_SYSCALL
        scripts/config --enable CONFIG_NETFILTER
        scripts/config --enable CONFIG_NETFILTER_ADVANCED
        scripts/config --enable CONFIG_NF_CONNTRACK

        # 启用 CGROUP 支持
        scripts/config --enable CONFIG_CGROUPS
        scripts/config --enable CONFIG_MEMCG
        scripts/config --enable CONFIG_CGROUP_FREEZER
        scripts/config --enable CONFIG_CGROUP_SCHED
        scripts/config --enable CONFIG_CGROUP_DEVICE

        # 启用 MTD
        scripts/config --enable CONFIG_MTD
        scripts/config --enable CONFIG_MTD_BLOCK
        scripts/config --enable CONFIG_MTD_CHAR
        scripts/config --enable CONFIG_MTD_CFI

        # 启用 GPIO
        scripts/config --enable CONFIG_GPIO_SYSFS

        # 启用 PHYLINK / SFP（用于某些网络设备）
        scripts/config --enable CONFIG_NET_DEVLINK
        scripts/config --enable CONFIG_PHYLINK
        scripts/config --enable CONFIG_SFP

        # 通用调试符号和 DWARF
        scripts/config --enable CONFIG_DEBUG_INFO
        scripts/config --enable CONFIG_DEBUG_INFO_DWARF4
        scripts/config --disable CONFIG_DEBUG_INFO_REDUCED
        scripts/config --disable CONFIG_STRIP_ASM_SYMS

        make olddefconfig

    - name: Build kernel and bzImage
      working-directory: kernel
      env:
        HOSTNAME: euler
        KBUILD_BUILD_USER: root
        KBUILD_BUILD_HOST: euler
      run: |
        make KCFLAGS=-g -j$(nproc)
        make KCFLAGS=-g bzImage
        ls -lh arch/x86/boot/bzImage vmlinux System.map

    - name: Upload bzImage
      uses: actions/upload-artifact@v4
      with:
        name: bzImage-x86
        path: kernel/arch/x86/boot/bzImage

    - name: Upload vmlinux
      uses: actions/upload-artifact@v4
      with:
        name: vmlinux-x86
        path: kernel/vmlinux

    - name: Upload System.map
      uses: actions/upload-artifact@v4
      with:
        name: System.map-x86
        path: kernel/System.map
