name: Build 32-bit x86 bzImage Kernel

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          gcc-10 g++-10 gcc-10-multilib g++-10-multilib \
          binutils binutils-i686-linux-gnu \
          bc bison flex libssl-dev libelf-dev dwarves \
          build-essential libncurses-dev \
          cmake git libdw-dev libdwarf-dev zlib1g-dev libiberty-dev

    - name: Build and install pahole v1.22
      run: |
        git clone https://git.kernel.org/pub/scm/devel/pahole/pahole.git -b v1.22
        cd pahole
        mkdir build && cd build
        cmake .. \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DCMAKE_INSTALL_LIBDIR=lib \
          -DEXEC_INSTALL_PREFIX= \
          -D__LIB=lib
        make -j$(nproc)
        sudo make install
        echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/dwarves.conf
        sudo ldconfig
        echo "LD_LIBRARY_PATH=/usr/local/lib" >> $GITHUB_ENV
        pahole --version
  
    - name: Set GCC and LD versions
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        echo "GCC Version:"
        gcc --version
        echo "LD Version:"
        ld --version

    - name: Clone kernel source
      run: |
        git clone https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git -b v5.10 kernel

    - name: Use i386_defconfig for real x86
      working-directory: kernel
      run: |
        make x86_64_defconfig
        
    - name: Enable CONFIG_DEBUG_INFO
      working-directory: kernel
      run: |
        # 1. 清理旧配置冲突
        sed -i '/CONFIG_BPF_/d' .config
        sed -i '/CONFIG_DEBUG_/d' .config
        sed -i '/CONFIG_MTD/d' .config
        sed -i '/CONFIG_GPIOLIB/d' .config

        # 2. 追加你的配置
        cat <<EOF >> .config
        # BPF 相关
        CONFIG_BPF_SYSCALL=y
        CONFIG_BPF_JIT=y
        CONFIG_CGROUP_BPF=y
        
        # 调试信息
        CONFIG_DEBUG_INFO=y
        CONFIG_DEBUG_INFO_DWARF4=y
        CONFIG_DEBUG_INFO_BTF=y
        CONFIG_PAHOLE_HAS_SPLIT_BTF=y
        CONFIG_PAHOLE_HAS_BTF_TAG=y
        
        # 网络设备
        CONFIG_NET_UDP_TUNNEL=y
        CONFIG_SFP=y
        CONFIG_PHYLINK=y
        
        # 内存管理
        CONFIG_MEMCG=y
        CONFIG_MEMCG_KMEM=y
        
        # IOMMU
        CONFIG_IOMMU_SUPPORT=y
        CONFIG_IOMMU_DEFAULT_DMA_STRICT=y
        
        # GPIO
        CONFIG_GPIOLIB=y
        CONFIG_GPIO_SYSFS=y
        
        # MTD
        CONFIG_MTD=y
        
        # 复位控制
        CONFIG_RESET_CONTROLLER=y
        
        # 其他调试
        CONFIG_DEBUG_KERNEL=y
        EOF

        

    - name: Build kernel and bzImage
      working-directory: kernel
      env:
        HOSTNAME: euler
        KBUILD_BUILD_USER: root
        KBUILD_BUILD_HOST: euler
      run: |
        make -j$(nproc)
        make bzImage
        ls -lh arch/x86/boot/bzImage vmlinux System.map

    - name: Upload bzImage
      uses: actions/upload-artifact@v4
      with:
        name: bzImage-x86
        path: kernel/arch/x86/boot/bzImage

    - name: Upload vmlinux
      uses: actions/upload-artifact@v4
      with:
        name: vmlinux-x86
        path: kernel/vmlinux

    - name: Upload System.map
      uses: actions/upload-artifact@v4
      with:
        name: System.map-x86
        path: kernel/System.map
