name: Build 32-bit x86 bzImage Kernel

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          gcc-10 g++-10 gcc-10-multilib g++-10-multilib \
          binutils binutils-i686-linux-gnu \
          bc bison flex libssl-dev libelf-dev dwarves \
          build-essential libncurses-dev

    - name: Set GCC and LD versions
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        echo "GCC Version:"
        gcc --version
        echo "LD Version:"
        ld --version

    - name: Clone kernel source from Gitee
      run: |
        git clone https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git -b v5.10 kernel

    - name: Use i386_defconfig for real x86
      working-directory: kernel
      run: |
        make ARCH=x86 i386_defconfig
        
    - name: Enable CONFIG_DEBUG_INFO
      working-directory: kernel
      run: |
        # BPF 相关
        echo "CONFIG_BPF_SYSCALL=y" >> .config
        echo "CONFIG_BPF_JIT=y" >> .config
        echo "CONFIG_CGROUP_BPF=y" >> .config

        # 网络设备
        echo "CONFIG_NET_UDP_TUNNEL=y" >> .config
        echo "CONFIG_SFP=y" >> .config
        echo "CONFIG_PHYLINK=y" >> .config
        
        echo "CONFIG_MEMCG=y" >> .config
        echo "CONFIG_MEMCG_KMEM=y" >> .config

        # IOMMU
        echo "CONFIG_IOMMU_SUPPORT=y" >> .config
        echo "CONFIG_IOMMU_DEFAULT_DMA_STRICT=y" >> .config

        # GPIO
        echo "CONFIG_GPIOLIB=y" >> .config
        echo "CONFIG_GPIO_SYSFS=y" >> .config

        # MTD
        echo "CONFIG_MTD=y" >> .config

        # 复位控制
        echo "CONFIG_RESET_CONTROLLER=y" >> .config

        # BTF
        echo "CONFIG_DEBUG_INFO_BTF=y" >> .config

        # 其他调试
        echo "CONFIG_DEBUG_KERNEL=y" >> .config
        echo "CONFIG_DEBUG_INFO=y" >> .config
        
        yes "" | make ARCH=x86 olddefconfig

    - name: Build kernel and bzImage
      working-directory: kernel
      env:
        ARCH: x86
        HOSTNAME: euler
        KBUILD_BUILD_USER: root
        KBUILD_BUILD_HOST: euler
      run: |
        make ARCH=$ARCH -j$(nproc)
        make ARCH=$ARCH bzImage
        ls -lh arch/x86/boot/bzImage vmlinux System.map

    - name: Upload bzImage
      uses: actions/upload-artifact@v4
      with:
        name: bzImage-x86
        path: kernel/arch/x86/boot/bzImage

    - name: Upload vmlinux
      uses: actions/upload-artifact@v4
      with:
        name: vmlinux-x86
        path: kernel/vmlinux

    - name: Upload System.map
      uses: actions/upload-artifact@v4
      with:
        name: System.map-x86
        path: kernel/System.map
