name: Build Kernel from Gitee

on:
  push:
    branches: [ main ]
  pull_request:


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-10 g++-10 bc bison flex libssl-dev make libelf-dev dwarves

    - name: Set GCC 10.3
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        gcc --version

    - name: Clone openeuler kernel from Gitee
      run: |
        git clone https://gitee.com/openeuler/kernel.git
        cd kernel
        git checkout OLK-5.10

    - name: Build Kernel
      working-directory: kernel
      run: |
        make defconfig
        make -j$(nproc)
        ls -lh vmlinux
        ls -lh System.map

    - name: Upload vmlinux artifact
      uses: actions/upload-artifact@v4
      with:
        name: vmlinux
        path: kernel/vmlinux

    - name: Upload System.map artifact
      uses: actions/upload-artifact@v4
      with:
        name: System.map
        path: kernel/System.map
